// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: replace apiKey and appId with values from Firebase Console →
  //       Project Settings → Your web app (add one if not yet created).
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC825h143G8V9VsE9G4Jec3DDBTUCBMzI0',
    appId: '1:130435149402:web:b02e654c0cf1d84311b263',
    messagingSenderId: '948878883710',
    projectId: 'fir-emoney-e9256',
    storageBucket: 'fir-emoney-e9256.firebasestorage.app',
    authDomain: 'fir-emoney-e9256.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWAzGMTyg1uSspi1qfno71sj4iCfp7qGk',
    appId: '1:948878883710:android:516b94bdc2276b68a0512f',
    messagingSenderId: '948878883710',
    projectId: 'fir-emoney-e9256',
    storageBucket: 'fir-emoney-e9256.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA46uBUvmVQKsSL7HIXZG58MD9jXQCFX7c',
    appId: '1:948878883710:ios:5363ad2b9fbe06b2a0512f',
    messagingSenderId: '948878883710',
    projectId: 'fir-emoney-e9256',
    storageBucket: 'fir-emoney-e9256.firebasestorage.app',
    iosBundleId: 'com.kampus.dompetKampusGlobal',
  );
}
